
server:
  port: 8082
spring:
  application:
    name: @artifactId@
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 127.0.0.1:8848
  #        username: nacos
  #        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bitstorm-svr?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: root@2023
  data:

    redis:
      host: localhost
      port: 6379
      password: root2023
      database: 0
      jedis:
        pool:
          max-active: 8 #?????
  kafka:
    #????????????????????Kafka???
    bootstrap-servers: 127.0.0.1:9092
    producer:
      # ??????????????
      retries: 0
      #???????????????????????????????????????????????????????????????
      batch-size: 16384
      # ??????????????
      buffer-memory: 33554432
      # ???????
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # ???????
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      # ????????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ????????
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #??????
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


send-msg-conf:
  mysql-as-mq : true
  open-cache: true
  max-retry-count: 5
  email-host: smtp.qq.com
  email-port: 587
  #??????
  email-account: xxx
  #??????
  email-auth-code: xxx
